/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Guillaume' at '19/07/16 23:19' with Gradle 2.14
 *
 * @author Guillaume, @date 19/07/16 23:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
